# Generated by Django 3.1.6 on 2024-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
